"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ConfidentialChatCompletionResponseTypedDict(TypedDict):
    r"""Response format for confidential chat completions"""

    ciphertext: str
    r"""The encrypted ChatCompletionResponse"""
    node_dh_public_key: str
    r"""Node's DH public key for key exchange"""
    nonce: str
    r"""Nonce used for encryption"""
    plaintext_body_hash: str
    r"""Hash of the plaintext body for verification"""
    salt: str
    r"""Salt used for encryption"""


class ConfidentialChatCompletionResponse(BaseModel):
    r"""Response format for confidential chat completions"""

    ciphertext: str
    r"""The encrypted ChatCompletionResponse"""

    node_dh_public_key: str
    r"""Node's DH public key for key exchange"""

    nonce: str
    r"""Nonce used for encryption"""

    plaintext_body_hash: str
    r"""Hash of the plaintext body for verification"""

    salt: str
    r"""Salt used for encryption"""
